<?php

/**
 * @file
 * Use to module mata_hari
 */

/**
 * Implements hook_menu()
 * 
 */
function mata_hari_menu() {
    $items['admin/config/mata_hari_info'] = array(
        'title' => 'Mata Hari',
        'page callback' => 'mata_hari_info_callback',
        'access arguments' => array('view mata_hari_info'),
    );
}

/**
 * Implements hook_permission().
 */
function mata_hari_permission() {
  $permissions = array(
    'view mata_hari_info' => array(
      'title' => t('View Informaton'),
    ),
  );
  return $permissions;
}
/**
 * Implements hook_entity_info
 * @return array
 */
function mata_hari_entity_info() {
    $info['mata_hari_info'] = array(
        'label' => t('Mata Hari entity'),
        'controller class' => 'EntityQuery',
        'base table' => 'mata_hari_info',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'id', // The 'id' (basic_id here) is the unique id.
        ),
        'static cache' => TRUE,
    );

    return $info;
}
