<?php

/**
 * @file
 * Use to module mata_hari_user
 */

/**
 * Implements hook_menu()
 * 
 * return array
 */
function mata_hari_menu() {
    $items = array();
    $items['admin/config/mata_hari/type/user'] = array(
        'title' => t('View log - User'),
        'page callback' => 'mata_hari_info_view_type',
        'page arguments' => array($item),
        'access arguments' => array('view mata_hari_info'),
        'file' => 'include/mata_hari.view.type.inc',
    );
    return $items;
}

/**
 * Implements hook_permission().
 * 
 * return array
 */
function mata_hari_permission() {
    $permissions = array(
        'view mata_hari' => array(
            'title' => t('View Informaton to mata hari.'),
        ),
        'config mata_hari' => array(
            'title' => t('Config information to mata hari.'),
        ),
    );
    return $permissions;
}

/**
 * Implements hook_entity_info
 * @return array
 */
function mata_hari_entity_info() {
    $info['mata_hari_info'] = array(
        'label' => t('Mata Hari entity'),
        'controller class' => 'EntityAPIController',
        'base table' => 'mata_hari_info',
        'fieldable' => TRUE,
        'entity keys' => array(
            'id' => 'id',
            'date' => 'date',
            'user' => 'user',
            'category' => 'category',
            'action' => 'action',
            'description' => 'description',
        ),
        'static cache' => TRUE,
    );

    return $info;
}

function mata_hari_tabs($results) {
    $header = array(
        array('data' => t('id')),
        array('data' => t('date')),
        array('data' => t('user')),
        array('data' => t('category')),
        array('data' => t('action')),
        array('data' => t('comment')),
    );


    if (isset($results) && $results != NULL) {
        foreach ($results as $result) {
            $user = user_load($result->user);
            $data['id'] = $result->id;
            $data['date'] = format_date($result->date, 'date_format_short');
            $data['user'] = l($user->name, 'user/' . $user->uid);
            $data['category'] = $result->category;
            $data['action'] = $result->action;
            $data['description'] = $result->description;
            $rows[] = array('data' => $data);
        }


        // build the table for the nice output.
        $build['tablesort_table'] = array(
            '#theme' => 'table',
            '#header' => $header,
            '#rows' => $rows,
        );
        return $build;
    } else {
        return FALSE;
    }
}
